### ISSUE TITLE
favicon generierung?

### ISSUE THREAD

**Issue by cukabeka** [TobiasKrais/d2u_helper#1]
Hi,

mir ist der Umfang des Addons noch nicht ganz klar, aber es scheint auch ein Favicon zu generieren, richtig? Wie wird das denn eingestellt?

**Comment by TobiasKrais** [comment]
Hi, generiert wird es nicht. Es muss einfach im Medienpool die Datei favicon.ico hochgeladen werden. Das ist noch etwas verbesserungswürdig...

**Comment by cukabeka** [comment]
Ah, gut zu wissen. 
Es gibt eine prima Klasse, die das erledigt: https://github.com/chrisbliss18/php-ico - würde hier gut passen..
Wobei das fast schon nützlich als separates Addon wäre :)

**Comment by cukabeka** [comment]
Was mich stutzen lässt, ist, dass ich aktuell das REDAXO-Error-Image vom Medienpool als favicon habe..

**Comment by TobiasKrais** [comment]
Siehe commit. Jetzt wird erst abgefragt, ob das Favicon auch existiert bevor es eingebunden wird.
