### ISSUE TITLE
Verbesserte Bildverwaltung für mehrsprachige D2U Linkboxen

### ISSUE THREAD

**Issue by SchneiderSam** [TobiasKrais/d2u_helper#12]
Hi @TobiasKrais,

ich hab leider nicht das D2U Linkboxen Repo gefunden, deswegen hier...

Ich möchte einen Vorschlag unterbreiten, wie wir die Bildverwaltung in D2U Linkboxen für mehrsprachige Webseiten verbessern können. Derzeit verwenden wir dasselbe Bild für alle Sprachversionen einer Seite. Aus SEO-Sicht wäre es jedoch effektiver, wenn jede Sprachversion ihr eigenes Bild hätte, das optimal benannt und genutzt wird.
![image](https://github.com/TobiasKrais/d2u_helper/assets/9355398/2443a996-f85a-4811-a910-0a426b4f115f)

**Vorschlag:**
1. **Sprachspezifische Bilder:**
   - Ermögliche es den Benutzern, separate Bilder für jede Sprachversion einer Seite innerhalb der D2U Linkbox-Einstellungen hochzuladen.

2. **SEO-Optimierung für Bilder:**
   - **Beschreibende Dateinamen:** Beispiel für jede Sprache: „ingenieurskunst-hoechstem-niveau-de.jpg“ für deutsche Seiten und „engineering-highest-level-en.jpg“ für englische Seiten. usw..
   - **Alt-Text:** Relevanten, lokalisierten Alternativtext (alt text) für jedes Bild bereitstellen.
   - **Titel und Bildunterschrift:** Wenn zutreffend, sicherstellen, dass Bildtitel und Bildunterschriften "übersetzbar" sind

**Vorteil:**
Die Umsetzung dieser Änderungen wird die SEO-Leistung von mehrsprachigen Seiten erheblich verbessern. Dieser lokalisierte Ansatz entspricht den besten SEO-Praktiken und bietet eine maßgeschneiderte Erfahrung für Benutzer in verschiedenen Regionen. Quelle: https://developers.google.com/search/docs/appearance/google-images?hl=de

**Aufgabenliste:**
- [ ] Funktion hinzufügen, um sprachspezifische Bilder in den D2U Linkbox-Einstellungen hochzuladen.
- [ ] Bild-Sitemaps generieren und aktualisieren, um sprachspezifische Bilder einzuschließen.

Ich freue mich auf dein Feedback und deine Gedanken zu diesem Vorschlag.

Liebe Grüße,
Samy

**Comment by skerbis** [comment]
Vorschlag: Dateinamen der Bilder je Sprache erfassen und es über einen rewriter lösen, z.B. mit URL2 - AddOn. 
Die Notwendigkeit je Sprache eigene Bilder hochzuladen sehe ich nicht. 
Allerdings sehe ich keinen Vorteil im SEO die Dateinamen in der jeweiligen Sprache zu schreiben , wenn die Bilder mit ALT-Tag in der Sprache ausgezeichnet sind

**Comment by SchneiderSam** [comment]
@skerbis 

Die Quelle die du nennst erklärt das gut:

> Achte bei der Lokalisierung deiner Bilder darauf, die Dateinamen zu übersetzen.

**Comment by TobiasKrais** [comment]
Dann mache ich den Issue zu. Bei Bedarf bitte wieder öffnen.

**Comment by skerbis** [comment]
@SchneiderSam  **my-new-black-kitten.jpg ist besser als IMG00023.JPG**. das ist erstmal wichtig. Ich würde nicht unnütz weitere gleiche Dateien mit gleichem Inhalt aber anderem Dateinamen hochladen. Die ALT-Info bietet sich hierfür an. Ich würde es nur machen wenn das Bild in der jeweiligen Sprache auch anders ist.

**Comment by SchneiderSam** [comment]
@skerbis Beschreibende Dateinamen wie `my-new-black-kitten.jpg` sind definitiv besser als generische Namen wie `IMG00023.JPG`. Die Lokalisierung der Dateinamen bietet jedoch zusätzliche Vorteile: Sie verbessert die Auffindbarkeit in der regionalen Bildersuche und erhöht die Benutzerfreundlichkeit, insbesondere für Nutzer, die die Sprache der Website sprechen. Google empfiehlt dies explizit zur besseren SEO-Optimierung (Siehe Screenshot). Während ALT-Tags und strukturierte Daten wichtig sind, bieten lokalisierte Dateinamen zusätzlichen Kontext und unterstützen eine umfassendere SEO-Strategie. Doppelte Inhalte sollten vermieden werden, es sei denn, die Bilder unterscheiden sich sprachspezifisch.

![image](https://github.com/TobiasKrais/d2u_helper/assets/9355398/a6979e76-24c0-4573-a553-becffb089b67)
Quelle: https://developers.google.com/search/docs/appearance/google-images?hl=de#descriptive-alt-text%20descriptive-titles-captions-filenames

**Comment by SchneiderSam** [comment]
> Im D2U Linkbox Addon gibt es schon die Funktion eines sprachbezogenen Bildes. Einfach die jeweilige Sprache aufklappen. Die letzte Eingabeposition ist das sprachbezogene Bild.

@TobiasKrais oha. Jetzt sehe ich das auch. Danke!

Hier fehlen aber noch die oben erwähnten Punkte:

- Alt-Text: Relevanten, lokalisierten Alternativtext (alt text) für jedes Bild (und jede Sprache) bereitstellen.
- Titel und Bildunterschrift: sicherstellen, dass Bildtitel und Bildunterschriften "übersetzbar" sind

Der Quellcode gibt zumindest die Daten nicht aus:
![image](https://github.com/TobiasKrais/d2u_helper/assets/9355398/efa1d105-4f61-4231-a611-f7a055428f06)

**Comment by TobiasKrais** [comment]
Der Alternativtext wird im Medienpool festgelegt. Es ist der Titel der dort eingegeben wird.

**Comment by skerbis** [comment]
@SchneiderSam @TobiasKrais gut aber das doppelte hochladen einer Datei sollte man vermeiden. (Unnützer Speicherverbrauch)  

Würde es so machen: 

Die Bilder erhalten je Sprache ein Metafeld für den Sprachdateinamen. Per URL2-AddOn stellt man diese URL dann in der jeweiligen Sprache zur Verfügung. Sie können dann auch in einer Sitemap bereitgestellt werden. 
Ein wenig PHP würde dafür sorgen dass in der jeweiligen Sprache dann die korrekte URL erscheint.
