### ISSUE TITLE
Option zur Zentrierung von Überschriften und Einfügen von Custom CSS in Modul 02-3

### ISSUE THREAD

**Issue by SchneiderSam** [TobiasKrais/d2u_helper#13]
Hi Tobi,

ich hoffe, dir geht’s gut! :-)

Ich hätte einen kleinen Verbesserungsvorschlag für die Redaxo-Erweiterung. Es wäre super, wenn wir die Möglichkeit hätten, die Überschriften im Modul "02-3 Überschrift mit Untertitel und Textfeld" zu zentrieren, ähnlich wie es bereits im Modul "02-1 Überschrift" möglich ist.

Aktuell wird im Modul "02-1 Überschrift" eine CSS-Klasse wie .heading-02-1-center verwendet (wenn die Option aktiviert ist), um die Überschrift zu zentrieren:
![image](https://github.com/user-attachments/assets/57d35651-ad6c-455f-8f40-ea96507605a2)

```
.heading-02-1-center {
    text-align: center;
}
```

Es wäre toll, wenn wir eine ähnliche Option für das Modul "02-3" hätten. Alternativ wäre es auch hilfreich, wenn man die Möglichkeit hätte, in jedes Modul Custom CSS einzufügen, um noch flexibler die Elemente gestalten zu können.

Was denkst du? Gibt es vielleicht noch andere Möglichkeiten, wie wir das umsetzen könnten?

Vielen Dank schon mal für deine Hilfe und die großartige Arbeit an der Erweiterung :-)

Grüße,
Samy

**Comment by SchneiderSam** [comment]
Nachtrag: Zum Beispiel eine Option wie "Texte/Elemente zentrieren". Nur die Überschrift zu zentrieren würde bei dem Modul wohl kein Sinn ergeben.

**Comment by TobiasKrais** [comment]
In den Einstellungen des Addons gibt es unter "Einstellungen für Template, Module und Menü" die Option "Zusätzlich eigenes CSS einbinden". Damit kann in die Templates dieses Addons passendes CSS integriert werden. Löst das dein Anliegen?
