### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by alxndr-w** [TobiasKrais/d2u_helper#4]
21.05.2021 21:53:38 | Notice | Trying to access array offset on value of type bool | redaxo/src/addons/d2u_helper/lib/d2u_module_manager.php | 232
-- | -- | -- | -- | --

PHP 7.4, aktuelle Version von d2u. Taucht mehrfach im Log auf.

**Comment by TobiasKrais** [comment]
Hmm. In der Version 1.8.4 ist in der Zeile 232 ein Kommentar. Kannst du mir bitte posten, was bei dir in der Zeile steht?

**Comment by alxndr-w** [comment]
Da es nicht mein Projekt ist, muss ich erstmal an die Datei kommen. Es muss die letzte Installer-Version gewesen sein.

**Comment by alxndr-w** [comment]
War Version 1.5.7 - das wird wahrscheinlich gar nicht mehr der Fall sein.

**Comment by TobiasKrais** [comment]
Alles klar. In der aktuellen Version habe ich auch unter PHP 8 keine Warnungen mehr.
