### ISSUE TITLE
Kanns unter 5.13 (MAMP lokal aufm Mac) nicht installieren

### ISSUE THREAD

**Issue by abra100pro** [TobiasKrais/d2u_helper#5]
Das ist die Fehlermeldung:

AddOn d2u_helper konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "INSERT INTO rex_media_manager_type (`status`, `name`, `description`) VALUES 01, 'd2u_helper_gallery_thumb', 'D2U Helper Bildergalerie Vorschaubild');": SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '01, 'd2u_helper_gallery_thumb', 'D2U Helper Bildergalerie Vorschaubild')' at line 2

**Comment by TobiasKrais** [comment]
Welche Version versuchst du zu installieren?

**Comment by TobiasKrais** [comment]
Hab gerade Version 1.8.9 veröffentlicht. Da müsste der Fehler behoben sein. Kannst du das bitte testen?

**Comment by abra100pro** [comment]
Geht leider noch nicht:

AddOn d2u_helper konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "INSERT INTO rex_media_manager_type (`status`, `name`, `description`) VALUES 0, 'd2u_helper_gallery_thumb', 'D2U Helper Bildergalerie Vorschaubild');": SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0, 'd2u_helper_gallery_thumb', 'D2U Helper Bildergalerie Vorschaubild')' at line 2

**Comment by TobiasKrais** [comment]
Gleich zwei Fehler in einem SQL Statement... Kannst du bitte das Addon nochmals löschen und neu aus dem Installer ziehen? Jetzt müsste es gehen.

**Comment by abra100pro** [comment]
Ja, wenn man's lesen kann ;-)...
Hat geklappt - ich konnte es jetzt problemlos installieren.
Danke.

**Comment by TobiasKrais** [comment]
Danke fürs melden und testen!
