### ISSUE TITLE
Call to a member function getValue() on null

### ISSUE THREAD

**Issue by staabm** [TobiasKrais/d2u_helper#7]
hab ich bekommen als ich eben das setup erneut ausgeführt hab und im DB step die option "update von vorheriger version" gewählt hab.

zu diesem zeitpunkt gibt es keinen eingeloggten user und daher läuft das addon auf diesen error

**Error:** Call to a member function getValue() on null
**File:** redaxo/src/addons/d2u_helper/lib/ALangHelper.php
**Line:** 85

<details>
<summary>Stacktrace</summary>

| Function                               | File                                                        | Line     |
| -------------------------------------- | ----------------------------------------------------------- | -------- |
| D2U_Helper\ALangHelper::saveValue      | redaxo/src/addons/d2u_helper/lib/d2u_helper_lang_helper.php | 610      |
| d2u_helper_lang_helper->install        | redaxo/src/addons/d2u_helper/install.php                    | 394      |
| require                                | redaxo/src/core/lib/packages/package.php                    | 233      |
| rex_package->includeFile               | redaxo/src/core/lib/packages/manager.php                    | 133      |
| rex_package_manager->install           | redaxo/src/core/lib/packages/addons/manager.php             | 22       |
| rex_addon_manager->install             | redaxo/src/core/lib/setup/import.php                        | 283      |
| rex_setup_importer::reinstallPackages  | redaxo/src/core/lib/setup/import.php                        | 32       |
| rex_setup_importer::updateFromPrevious | redaxo/src/core/pages/setup.php                             | 207      |
| include                                | redaxo/src/core/lib/be/controller.php                       | 490      |
| rex_be_controller::{closure}           | redaxo/src/core/lib/util/timer.php                          | 62       |
| rex_timer::measure                     | redaxo/src/core/lib/be/controller.php                       | 498      |
| rex_be_controller::includePath         | redaxo/src/core/lib/be/controller.php                       | 430      |
| rex_be_controller::includeCurrentPage  | redaxo/src/core/backend.php                                 | 235      |
| require                                | redaxo/src/core/boot.php                                    | 148      |
| require                                | redaxo/index.php                                            | 9        |

</details>
<details>
<summary>System report (REDAXO 5.15.0-dev#8baa10502, PHP 8.1.16, MariaDB 10.10.3)</summary>

| REDAXO        |                      |
| ------------: | :------------------- |
|       Version | 5.15.0-dev#8baa10502 |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 8.1.16                         |
|       OPcache | yes                            |
|        Xdebug | yes                            |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.10.3 |
| Character set | utf8mb4         |

| Server        |                |
| ------------: | :------------- |
|            OS | Darwin         |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.55  |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/112.0 |
|      Protocol | HTTP/1.1      |
|         HTTPS | no            |

| Packages          |              |
| ----------------: | :----------- |
|           adminer | 1.9.2        |
|            backup | 2.8.3-dev    |
|          be_style | 3.1.1        |
|   be_style/redaxo | 3.1.1        |
|        d2u_helper | 1.9.3        |
|     d2u_machinery | 1.3.7        |
|         developer | 3.9.1        |
|           install | 2.10.1-dev   |
|     media_manager | 2.13.2       |
|         mediapool | 2.12.0       |
|          metainfo | 2.9.0        |
|           project | dev          |
|           rexstan | 1.0.82-beta3 |
|    rexstansqltest | 0.0.0        |
|             sprog | 1.4.0        |
|         structure | 2.14.3-dev   |
| structure/content | 2.14.3-dev   |
|               url | 2.0.2        |
|             users | 2.9.1        |
|            watson | 2.3.0        |
|             yform | 4.0.4        |
|       yform/email | 4.0.4        |
|     yform/manager | 4.0.4        |
|          yrewrite | 2.9.1        |

</details>

**Comment by TobiasKrais** [comment]
Danke für den Bugreport. Ich überarbeite das Addon gerade mit rexstan. Da wurde der Fehler schon lokalisert und behoben:
- https://github.com/TobiasKrais/d2u_helper/blob/38678d21b4cd120e3dc87b80d7ced5af47d4c08d/lib/ALangHelper.php#L72
-https://github.com/TobiasKrais/d2u_helper/blob/38678d21b4cd120e3dc87b80d7ced5af47d4c08d/lib/ALangHelper.php#L87-L89

Es dauert noch ein paar Wochen, bis ich komplett durch das Addon durch bin. Meinst du ich soll in der Zwischenzeit schon mal ein Release machen?

**Comment by staabm** [comment]
Freut mich das dir rexstan helfen konnte den fehler zu finden :-). 

Wg mir brauchst du kein release machen.. ich hab das addon nur in meinem dev testing setup wo der fehler mich nicht behindert

**Comment by TobiasKrais** [comment]
Alles klar. Danke. Und: rexstan ist absolut Spitze!
