### ISSUE TITLE
bei mkdir falscher Wert für die Rechtevergabe

### ISSUE THREAD

**Issue by clausbde** [TobiasKrais/d2u_helper#8]
v1.10.0

In Zeile 243 und 277 muss

`mkdir(rex_path::addonCache('d2u_helper'), 0o755, true);`

ersetzt werden durch

`mkdir(rex_path::addonCache('d2u_helper'), 0755, true);`

Das "o" in 0**o**755 ist falsch.

**Comment by TobiasKrais** [comment]
Autsch, wie ist das den passiert. Danke für die Meldung. Update kommt nachher in den Installer.

**Comment by clausbde** [comment]
Danke für die schnelle Reaktion. :)
