### ISSUE TITLE
Fehler beim update von d2u_news und d2u_staff

### ISSUE THREAD

**Issue by olien** [TobiasKrais/d2u_helper#9]
![image](https://github.com/TobiasKrais/d2u_news/assets/330516/42e9d211-39d8-4081-951f-00c20a2d40f6)

<details>
<summary>System report (REDAXO 5.16.0, PHP 8.3.0, MariaDB 10.3.39)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.16.0     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.3.0      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                                |
| ------------: | :----------------------------- |
|       Version | MariaDB 10.3.39                |
| Character set | utf8                           |
|       Warning | Die verwendete MariaDB-Version 10.3.39 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/17.0 |
|      Protocol | HTTP/2.0    |
|         HTTPS | yes         |

| Packages                   |            |
| -------------------------: | :--------- |
|               accessdenied | 2.1.0      |
|                    adminer | 1.9.3      |
|                     backup | 2.9.1      |
|                be_password | 2.0.1      |
|                   be_style | 3.3.0      |
|        be_style/customizer | 3.3.0      |
|            be_style/redaxo | 3.3.0      |
|                    bloecks | 3.1.1      |
|           bloecks/cutncopy | 3.1.1      |
|             bloecks/status | 3.1.1      |
|            consent_manager | 4.2.0      |
|                    cronjob | 2.10.1     |
|                 d2u_helper | 1.13.0     |
|                   d2u_news | 1.1.4      |
|                  d2u_staff | 1.1.0      |
|                      debug | 1.3.0      |
|                  developer | 3.9.2      |
|              fa_iconpicker | 1.2.0      |
|                    install | 2.12.0     |
|               lightgallery | 0.4.3      |
|                maintenance | 2.9.2      |
|                   markitup | 3.7.4      |
|     markitup/documentation | 1.1.0      |
|              media_manager | 2.15.0     |
|                  mediapool | 2.13.1     |
|           mediapool_rename | 1.0.0      |
|                   metainfo | 2.10.1     |
|                      mform | 7.3.3      |
|              modulsammlung | 4.16.0     |
|         navigation_factory | 2.0.3      |
|                     pdfout | 8.1.1      |
|                  phpmailer | 2.13.0     |
|                    project | dev        |
|            project_manager | 1.5.1      |
|     project_manager/client | 1.1.0      |
|                  redactor2 | 4.2.1      |
|                  search_it | 6.10.1     |
|     search_it/autocomplete | 6.10.1     |
|    search_it/documentation | 6.10.1     |
|        search_it/plaintext | 6.10.1     |
|            search_it/stats | 6.10.1     |
|                      sprog | 1.5.1      |
|                  structure | 2.16.0     |
|          structure/content | 2.16.0     |
|          structure/history | 2.16.0     |
|                      theme | 1.4.0      |
|                   tinymce4 | 1.2.1      |
|                   ui_tools | 1.2.2      |
| ui_tools/jquery-minicolors | 2.4.0      |
|                      users | 2.10.1     |
|                       ycom | 4.2.1      |
|                  ycom/auth | 4.2.1      |
|                 ycom/group | 4.2.1      |
|            ycom/media_auth | 4.2.1      |
|                      yform | 4.1.1      |
|                yform/email | 4.1.1      |
|              yform/manager | 4.1.1      |
|                yform/tools | 4.1.1      |
|                   yrewrite | 2.10.0     |

</details>

**Comment by TobiasKrais** [comment]
Ja, da war in einer älteren Version ein Bug drin. Du musst das d2u_news und d2u_staff Addon vor dem Update deaktivieren und danach wieder aktivieren. Dann klappt es.

**Comment by TobiasKrais** [comment]
Müsste in den Updatehinweisen stehen.

**Comment by olien** [comment]
Ah. DANKE steh drin. Habs nicht gelesen :-( Sorry

**Comment by TobiasKrais** [comment]
Kein Problem. Ist ein dummer Fehler von mir gewesen.
